Add Simplified Chinese (简体中文) translation
orblazer/plasma-applet-resources-monitor pull request #94
Opened 2024-10-31 16:28 UTC by Starrah

2024-11-26 13:22 UTC, Starrah commented
Update: added new commit d1c3201 just now, which adds new i18n items: `i18n("RAM")` and `i18n("VRAM")`, for translation in the graph label hints. 
![image](https://github.com/user-attachments/assets/8ddce73a-11b1-46be-8e0c-47bfa208a851)
![image](https://github.com/user-attachments/assets/8f667195-1222-4f46-be4b-46bc33d73dac)

2025-04-07 03:50 UTC, orblazer requested changes

2025-04-07 03:50 UTC, orblazer commented on package/contents/ui/components/graph/GpuGraph.qml
> +        hints: ["GPU", (secondChartVisible ? i18n("VRAM") : ""), (showTemp ? i18nc("Graph label", "Temp.") : "")]
This should be use `i18nc` with `Graph label` category.

2025-04-07 03:50 UTC, orblazer commented on package/contents/ui/components/graph/MemoryGraph.qml
> +        hints: [i18n("RAM"), root.showSwap ? i18n("Swap") : (sensorsType[1] === "memory-percent" ? i18nc("Graph label", "Percent.") : ""), ""]
This should be use `i18nc` with `Graph label` category.

2025-08-01 12:11 UTC, orblazer commented
Hello, could you update your PR with last version and with the requested change ?

2025-08-01 12:16 UTC, Starrah commented
Sorry, I was busy with my job and regret that I forgot it. I will update the PR in a few days.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年8月1日(周五) 晚上8:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [orblazer/plasma-applet-resources-monitor] Add Simplified Chinese (简体中文) translation (PR #94)


orblazer left a comment (orblazer/plasma-applet-resources-monitor#94)
 
Hello, could you update your PR with last version and with the requested change ?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2025-11-01 16:20 UTC, orblazer commented
Hello,
Could you update that PR or i can simply close it ?

2025-11-02 06:05 UTC, Starrah commented
Sorry for the late response, I have update the commit as your request, and update the translations to the latest version on master.

2025-11-30 22:36 UTC, orblazer commented
Hello, i going to close this PR caused it seem to be polluted for unknown reason. Feel free to open an new PR and i'm sorry for that issue.

2025-11-30 22:36 UTC, closed without merging